#define USB_POLLING_INTERVAL_MS 1
#undef DEBOUNCE
#define DEBOUNCE 40
/*#define DEBUG_MATRIX_SCAN_RATE*/

#define USB_MAX_POWER_CONSUMPTION 50

#ifdef AUDIO_VOICES
#undef AUDIO_VOICES
#endif

#define UNICODE_KEY_WINC KC_APP
#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE

#define DYNAMIC_KEYMAP_LAYER_COUNT 10
