#define USB_POLLING_INTERVAL_MS 1
#define QMK_KEYS_PER_SCAN 8
#ifdef DEBOUNCE
#undef DEBOUNCE
#endif
#define DEBOUNCE 40

#define USB_MAX_POWER_CONSUMPTION 50
#ifdef AUDIO_VOICES
#undef AUDIO_VOICES
#endif

#ifdef DYNAMIC_KEYMAP_LAYER_COUNT
#undef DYNAMIC_KEYMAP_LAYER_COUNT
#endif
#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
