#define USB_POLLING_INTERVAL_MS 1

#ifdef DEBOUNCE
#undef DEBOUNCE
#endif
#define DEBOUNCE 40

#ifdef DYNAMIC_KEYMAP_LAYER_COUNT
#undef DYNAMIC_KEYMAP_LAYER_COUNT
#endif
#define DYNAMIC_KEYMAP_LAYER_COUNT 8
