#pragma once

#ifdef DYNAMIC_KEYMAP_LAYER_COUNT
#undef DYNAMIC_KEYMAP_LAYER_COUNT
#endif
#define DYNAMIC_KEYMAP_LAYER_COUNT 10

#ifdef DEBOUNCE
#undef DEBOUNCE
#endif
#define DEBOUNCE 40

#define RGB_MATRIX_KEYHOLDS
#define LED_HITS_TO_REMEMBER 40
